gxmons_r: MACRO
    dw POOCHYENA
    dw ZIGZAGOON
    dw LINOONE
    dw SEEDOT
    dw TAILLOW
    dw SWELLOW
    dw WINGULL
    dw RALTS
    dw SURSKIT
    dw SHROOMISH
    dw SLAKOTH
    dw ABRA
    dw NINCADA
    dw WHISMUR
    dw LOUDRED
    dw MAKUHITA
    dw GOLDEEN
    dw MAGIKARP
    dw MARILL
    dw GEODUDE
    dw NOSEPASS
    dw SKITTY
    dw ZUBAT
    dw TENTACOOL
    dw MAWILE
    dw ARON
    dw MACHOP
    dw MEDITITE
    dw ELECTRIKE
    dw PLUSLE
    dw MINUN
    dw MAGNEMITE
    dw VOLTORB
    dw VOLBEAT
    dw ILLUMISE
    dw ODDISH
    dw DODUO
    dw ROSELIA
    dw GULPIN
    dw CARVANHA
    dw WAILMER
    dw NUMEL
    dw SLUGMA
    dw TORKOAL
    dw GRIMER
    dw KOFFING
    dw SPOINK
    dw SANDSHREW
    dw SPINDA
    dw SKARMORY
    dw TRAPINCH
    dw CACNEA
    dw SWABLU
    dw ZANGOOSE
    dw SOLROCK
    dw BARBOACH
    dw CORPHISH
    dw BALTOY
    dw JIGGLYPUFF
    dw FEEBAS
    dw STARYU
    dw KECLEON
    dw DUSKULL
    dw TROPIUS
    dw CHIMECHO
    dw ABSOL
    dw VULPIX
    dw PIKACHU
    dw PSYDUCK
    dw NATU
    dw GIRAFARIG
    dw PHANPY
    dw PINSIR
    dw HERACROSS
    dw RHYHORN
    dw SNORUNT
    dw SPHEAL
    dw CLAMPERL
    dw RELICANTH
    dw CORSOLA
    dw CHINCHOU
    dw LUVDISC
    dw HORSEA
    dw BAGON
    ; 84
    dw SHADOW_BALL
    dw FACADE
    dw HYPER_BEAM
    dw BULLET_SEED
    dw STEEL_WING
    dw DOUBLE_TEAM
    dw RAIN_DANCE
    dw CALM_MIND
    dw ICE_BEAM
    dw SLUDGE_BOMB
    dw SECRET_POWER
    dw HIDDEN_POWER
    dw AERIAL_ACE
    dw ROAR
    dw SHOCK_WAVE
    dw BRICK_BREAK
    dw WATER_PULSE
    dw SPLASH
    dw BLIZZARD
    dw ROCK_TOMB
    dw EARTHQUAKE
    dw IRON_TAIL
    dw SLUDGE_BOMB
    dw HAIL
    dw TAUNT
    dw ROCK_TOMB
    dw BRICK_BREAK
    dw SKILL_SWAP
    dw THUNDERBOLT
    dw RETURN
    dw RETURN
    dw THUNDER
    dw RAIN_DANCE
    dw SHOCK_WAVE
    dw SHOCK_WAVE
    dw TOXIC
    dw HIDDEN_POWER
    dw GIGA_DRAIN
    dw REST
    dw TORMENT
    dw WATER_PULSE
    dw EARTHQUAKE
    dw SUNNY_DAY
    dw FIRE_BLAST
    dw TOXIC
    dw FLAMETHROWER
    dw SNATCH
    dw PROTECT
    dw FOCUS_PUNCH
    dw DOUBLE_TEAM
    dw SANDSTORM
    dw BULLET_SEED
    dw SAFEGUARD
    dw DIG
    dw PSYCHIC
    dw EARTHQUAKE
    dw THIEF
    dw SECRET_POWER
    dw FACADE
    dw ATTRACT
    dw PSYCHIC
    dw SNATCH
    dw THIEF
    dw SOLARBEAM
    dw LIGHT_SCREEN
    dw SHADOW_BALL
    dw OVERHEAT
    dw LIGHT_SCREEN
    dw AERIAL_ACE
    dw REFLECT
    dw REFLECT
    dw IRON_TAIL
    dw BULK_UP
    dw FOCUS_PUNCH
    dw ROAR
    dw HAIL
    dw PROTECT
    dw REST
    dw ROCK_TOMB
    dw CALM_MIND
    dw THUNDER
    dw FRUSTRATION
    dw ICE_BEAM
    dw DRAGON_CLAW
    ENDM
gxmons_s: MACRO
    dw POOCHYENA
    dw ZIGZAGOON
    dw LINOONE
    dw LOTAD
    dw TAILLOW
    dw SWELLOW
    dw WINGULL
    dw RALTS
    dw SURSKIT
    dw SHROOMISH
    dw SLAKOTH
    dw ABRA
    dw NINCADA
    dw WHISMUR
    dw LOUDRED
    dw MAKUHITA
    dw GOLDEEN
    dw MAGIKARP
    dw MARILL
    dw GEODUDE
    dw NOSEPASS
    dw SKITTY
    dw ZUBAT
    dw TENTACOOL
    dw SABLEYE
    dw ARON
    dw MACHOP
    dw MEDITITE
    dw ELECTRIKE
    dw PLUSLE
    dw MINUN
    dw MAGNEMITE
    dw VOLTORB
    dw VOLBEAT
    dw ILLUMISE
    dw ODDISH
    dw DODUO
    dw ROSELIA
    dw GULPIN
    dw CARVANHA
    dw WAILMER
    dw NUMEL
    dw SLUGMA
    dw TORKOAL
    dw GRIMER
    dw KOFFING
    dw SPOINK
    dw SANDSHREW
    dw SPINDA
    dw SKARMORY
    dw TRAPINCH
    dw CACNEA
    dw SWABLU
    dw SEVIPER
    dw LUNATONE
    dw BARBOACH
    dw CORPHISH
    dw BALTOY
    dw JIGGLYPUFF
    dw FEEBAS
    dw STARYU
    dw KECLEON
    dw DUSKULL
    dw TROPIUS
    dw CHIMECHO
    dw ABSOL
    dw VULPIX
    dw PIKACHU
    dw PSYDUCK
    dw NATU
    dw GIRAFARIG
    dw PHANPY
    dw PINSIR
    dw HERACROSS
    dw RHYHORN
    dw SNORUNT
    dw SPHEAL
    dw CLAMPERL
    dw RELICANTH
    dw CORSOLA
    dw CHINCHOU
    dw LUVDISC
    dw HORSEA
    dw BAGON
    ; 84
    dw SHADOW_BALL
    dw FACADE
    dw HYPER_BEAM
    dw BULLET_SEED
    dw STEEL_WING
    dw DOUBLE_TEAM
    dw RAIN_DANCE
    dw CALM_MIND
    dw ICE_BEAM
    dw SLUDGE_BOMB
    dw SECRET_POWER
    dw HIDDEN_POWER
    dw AERIAL_ACE
    dw ROAR
    dw SHOCK_WAVE
    dw BRICK_BREAK
    dw WATER_PULSE
    dw SPLASH
    dw BLIZZARD
    dw ROCK_TOMB
    dw EARTHQUAKE
    dw IRON_TAIL
    dw SLUDGE_BOMB
    dw HAIL
    dw TAUNT
    dw ROCK_TOMB
    dw BRICK_BREAK
    dw SKILL_SWAP
    dw THUNDERBOLT
    dw RETURN
    dw RETURN
    dw THUNDER
    dw RAIN_DANCE
    dw SHOCK_WAVE
    dw SHOCK_WAVE
    dw TOXIC
    dw HIDDEN_POWER
    dw GIGA_DRAIN
    dw REST
    dw TORMENT
    dw WATER_PULSE
    dw EARTHQUAKE
    dw SUNNY_DAY
    dw FIRE_BLAST
    dw TOXIC
    dw FLAMETHROWER
    dw SNATCH
    dw PROTECT
    dw FOCUS_PUNCH
    dw DOUBLE_TEAM
    dw SANDSTORM
    dw BULLET_SEED
    dw SAFEGUARD
    dw DIG
    dw PSYCHIC
    dw EARTHQUAKE
    dw THIEF
    dw SECRET_POWER
    dw FACADE
    dw ATTRACT
    dw PSYCHIC
    dw SNATCH
    dw THIEF
    dw SOLARBEAM
    dw LIGHT_SCREEN
    dw SHADOW_BALL
    dw OVERHEAT
    dw LIGHT_SCREEN
    dw AERIAL_ACE
    dw REFLECT
    dw REFLECT
    dw IRON_TAIL
    dw BULK_UP
    dw FOCUS_PUNCH
    dw ROAR
    dw HAIL
    dw PROTECT
    dw REST
    dw ROCK_TOMB
    dw CALM_MIND
    dw THUNDER
    dw FRUSTRATION
    dw ICE_BEAM
    dw DRAGON_CLAW
    ENDM
asmstore: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $64
    db $00
    db $00
    db $02
    db $41
    db $54
    db $12
    db $08
    ENDM
asmstore_rev: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $64
    db $00
    db $00
    db $02
    db $61
    db $54
    db $12
    db $08
    ENDM
asmread_r: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $F9
    db $5B
    db $12
    db $08
    ENDM
asmread_r_r1: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $19
    db $5C
    db $12
    db $08
    ENDM
asmread_r_r2: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $19
    db $5C
    db $12
    db $08
    ENDM
asmread_s: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $F9
    db $5B
    db $12
    db $08
    ENDM
asmread_s_r1: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $19
    db $5C
    db $12
    db $08
    ENDM
asmread_s_r2: MACRO
    db $1E
    db $20
    db $01
    db $49
    db $01
    db $4A
    db $10
    db $47
    db $20
    db $A0
    db $01
    db $02
    db $19
    db $5C
    db $12
    db $08
    ENDM