HIKER        EQU $00
TEAM_AQUA_M  EQU $01 ; TEAM AQUA*
PKMN_BREEDER_F EQU $02 ; \{PKMN} BREEDER
COOLTRAINER_M EQU $03 ; COOLTRAINER♂
BIRD_KEEPER  EQU $04
COLLECTOR    EQU $05
TEAM_AQUA_F  EQU $06 ; TEAM AQUA*
SWIMMER_M    EQU $07 ; SWIMMER♂
TEAM_MAGMA_M EQU $08 ; *
EXPERT_M     EQU $09 ; EXPERT
TC_BLACK_BELT EQU $0A ; item name
AQUA_LEADER  EQU $0B ; *
HEX_MANIAC   EQU $0C
AROMA_LADY   EQU $0D
RUIN_MANIAC  EQU $0E
INTERVIEWER  EQU $0F ; *
TUBER_F      EQU $10 ; TUBER
TUBER_M      EQU $11 ; TUBER
COOLTRAINER_F EQU $12 ; COOLTRAINER♀
LADY         EQU $13
BEAUTY       EQU $14
RICH_BOY     EQU $15
EXPERT_F     EQU $16 ; EXPERT
POKEMANIAC   EQU $17 ; POKéMANIAC
TEAM_MAGMA_F EQU $18 ; *
GUITARIST    EQU $19
KINDLER      EQU $1A
CAMPER       EQU $1B
PICNICKER    EQU $1C
BUG_MANIAC   EQU $1D
PSYCHIC_M    EQU $1E ; PSYCHIC
PSYCHIC_F    EQU $1F ; PSYCHIC
GENTLEMAN    EQU $20
ELITE_FOUR_SIDNEY EQU $21 ; ELITE FOUR*
ELITE_FOUR_PHOEBE EQU $22 ; ELITE FOUR*
LEADER_ROXANNE   EQU $23 ; LEADER*
LEADER_BRAWLY    EQU $24 ; LEADER*
LEADER_TATE_LIZA EQU $25 ; LEADER*
SCHOOL_KID_M EQU $26 ; SCHOOL KID
SCHOOL_KID_F EQU $27 ; SCHOOL KID
SR_AND_JR    EQU $28 ; SR. AND JR.*
POKEFAN_M    EQU $29 ; POKéFAN
POKEFAN_F    EQU $2A ; POKéFAN
YOUNGSTER    EQU $2B
CHAMPION     EQU $2C ; *
FISHERMAN    EQU $2D
TRIATHLETE_M_BIKE EQU $2E ; TRIATHLETE
TRIATHLETE_F_BIKE EQU $2F ; TRIATHLETE
TRIATHLETE_M_RUN  EQU $30 ; TRIATHLETE
TRIATHLETE_F_RUN  EQU $31 ; TRIATHLETE
TRIATHLETE_M_SWIM EQU $32 ; TRIATHLETE
TRIATHLETE_F_SWIM EQU $33 ; TRIATHLETE
DRAGON_TAMER EQU $34
NINJA_BOY    EQU $35
BATTLE_GIRL  EQU $36
PARASOL_LADY EQU $37
SWIMMER_F    EQU $38 ; SWIMMER♀
TWINS        EQU $39 ; *
SAILOR       EQU $3A
PKMN_TRAINER_WALLY     EQU $3B ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_1 EQU $3C ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_2 EQU $3D ; \{PKMN} TRAINER*
PKMN_TRAINER_BRENDAN_3 EQU $3E ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_1     EQU $3F ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_2     EQU $40 ; \{PKMN} TRAINER*
PKMN_TRAINER_MAY_3     EQU $41 ; \{PKMN} TRAINER*
PKMN_BREEDER_M EQU $42 ; \{PKMN} BREEDER
BUG_CATCHER  EQU $43
PKMN_RANGER_M  EQU $44 ; \{PKMN} RANGER
PKMN_RANGER_F  EQU $45 ; \{PKMN} RANGER
MAGMA_LEADER EQU $46 ; *
LASS         EQU $47
YOUNG_COUPLE EQU $48 ; *
OLD_COUPLE   EQU $49 ; *
SIS_AND_BRO  EQU $4A ; *
POKEMON_TRAINER_STEVEN    EQU $4B ; *
SALON_MAIDEN_ANABEL    EQU $4C ; *
DOME_ACE_TUCKER    EQU $4D
POKEMON_TRAINER_RED    EQU $4E
POKEMON_TRAINER_GREEN    EQU $4F